backend:
name: git-gateway
branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
- name: "articles"
label: "Articles & Blog"
folder: "_articles"
create: true
slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
fields:
- {label: "Title", name: "title", widget: "string"}
- {label: "Author", name: "author", widget: "string", default: "Abdisa Kedir"}
- {label: "Date", name: "date", widget: "datetime"}
- {label: "Body", name: "body", widget: "markdown"}